-- Todoro sync schema.
--
-- The app is local-first: localStorage stays the synchronous source of truth
-- that the UI reads and writes, and these tables are a replica reconciled in
-- the background. Signing in is optional, so nothing here is on the critical
-- path for a signed-out user.
--
-- Normalized rows rather than one JSON document per user, for three reasons
-- specific to this app: the custom alert sound is a ~700KB data-URL and the
-- avatar a ~20KB one, so toggling a daily goal must not re-upload an audio
-- file; history grows without bound and needs append-only idempotent writes;
-- and a single document forces conflict resolution at whole-account
-- granularity, which is guaranteed multi-device data loss.

create extension if not exists pgcrypto;

-- Server clock is the only clock. A client-supplied updated_at is discarded, so
-- a device whose clock is days fast cannot win every conflict forever. Ordering
-- across devices is decided by arrival here, which is immune to clock skew.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end
$$;

-- ── projects ────────────────────────────────────────────────────────────────
create table public.projects (
  user_id    uuid        not null default auth.uid()
                         references auth.users(id) on delete cascade,
  id         text        not null,
  name       text        not null default '',
  color      text        not null default '#6366f1',
  deleted_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index projects_pull_idx on public.projects (user_id, updated_at);

-- ── tasks ───────────────────────────────────────────────────────────────────
-- `id` is text, not uuid: existing ids were generated by Math.random and are
-- opaque strings nothing parses, so they stay valid and there is no migration.
--
-- No due_label column. That string is rendered at save time and never
-- recomputed, so it is already stale on the device that wrote it; syncing it
-- would propagate one device's staleness to another. It is recomputed from
-- due_date/due_time when a row is applied.
--
-- No foreign key on project_id. An FK would force topological push ordering and
-- partial-failure recovery; without one every push is independently retryable.
-- The app already tolerates a dangling projectId — deleting a project clears it
-- on member tasks, and lookups use find() which returns undefined safely.
create table public.tasks (
  user_id            uuid        not null default auth.uid()
                                 references auth.users(id) on delete cascade,
  id                 text        not null,
  title              text        not null default '',
  priority           text        not null default 'none'
                       check (priority in ('high', 'mid', 'low', 'none')),
  -- Local calendar strings, deliberately not `date`/`time`: due dates are
  -- wall-clock facts in the user's timezone, and round-tripping them through
  -- UTC would shift them across midnight on a device in another zone.
  due_date           text,
  due_time           text,
  done               boolean     not null default false,
  subtasks           jsonb       not null default '[]'::jsonb,
  estimated_sessions integer     not null default 0,
  completed_sessions integer     not null default 0,
  project_id         text,
  repeat             text        not null default 'none'
                       check (repeat in ('none', 'daily', 'weekly')),
  stage              text        check (stage in ('todo', 'doing')),
  deleted_at         timestamptz,
  updated_at         timestamptz not null default now(),
  primary key (user_id, id),
  constraint tasks_subtasks_is_array check (jsonb_typeof(subtasks) = 'array'),
  -- Defence in depth: the quick-focus sentinel is only ever an active task,
  -- never a stored one.
  constraint tasks_id_not_reserved check (id <> 'quick-mode')
);
create index tasks_pull_idx on public.tasks (user_id, updated_at);

-- ── sessions ────────────────────────────────────────────────────────────────
-- Append-only and immutable. `key` is a deterministic natural key rather than a
-- random id, which makes pushes idempotent under at-least-once delivery and
-- makes re-importing a backup deduplicate instead of doubling the streak.
--
-- `at` stays bigint. Streaks are counted in the user's local calendar day, so
-- the client's epoch ms is preserved verbatim; converting to timestamptz and
-- back through a different device timezone would move sessions across day
-- boundaries and silently break streaks.
--
-- No FK on task_id: it can be the quick-focus sentinel, or a task since
-- deleted. task_title is already denormalized on the client for this reason.
create table public.sessions (
  user_id    uuid        not null default auth.uid()
                         references auth.users(id) on delete cascade,
  key        text        not null,
  task_id    text        not null,
  task_title text        not null default '',
  focus_mins integer     not null,
  at         bigint      not null,
  created_at timestamptz not null default now(),
  primary key (user_id, key)
);
create index sessions_pull_idx on public.sessions (user_id, created_at);

-- ── point_ops ───────────────────────────────────────────────────────────────
-- Points and freezes are counters, and last-write-wins on a counter destroys
-- increments: +80 earned offline on one device and +50 on another becomes 80,
-- not 130. Storing deltas in an append-only log makes them conflict-free.
--
-- `id` is client-generated with NO default, deliberately. At-least-once
-- delivery plus a counter double-counts: a push that succeeds but whose
-- response is lost gets retried and the user gains phantom points. The client
-- mints the id and persists it before the request goes out, so a retry reuses
-- it and `on conflict (id) do nothing` makes the retry a no-op.
create table public.point_ops (
  id            uuid        primary key,
  user_id       uuid        not null default auth.uid()
                            references auth.users(id) on delete cascade,
  points_delta  integer     not null default 0,
  freeze_delta  integer     not null default 0,
  protected_add text[]      not null default '{}',
  device_id     text,
  created_at    timestamptz not null default now()
);
create index point_ops_pull_idx on public.point_ops (user_id, created_at);

-- ── settings ────────────────────────────────────────────────────────────────
-- One wide row per user, every column nullable, patched per field so that a
-- device changing the theme and another changing the daily goal both survive.
-- Only the same field on both devices can conflict.
create table public.settings (
  user_id       uuid        primary key default auth.uid()
                            references auth.users(id) on delete cascade,
  user_name     text,
  daily_goal    integer,
  theme         text,
  accent_theme  text,
  accent_custom jsonb,
  mode          text,
  focus_mins    integer,
  break_mins    integer,
  sound         boolean,
  alert_sound   text,
  alert_volume  real,
  quick_mode    boolean,
  reverse_mode  boolean,
  auto_start    boolean,
  pinned        text[]      not null default '{}',
  updated_at    timestamptz not null default now()
);

-- ── user_assets ─────────────────────────────────────────────────────────────
-- The two large data-URLs, isolated so they never ride a settings write.
create table public.user_assets (
  user_id    uuid        not null default auth.uid()
                         references auth.users(id) on delete cascade,
  kind       text        not null check (kind in ('avatar', 'alert_sound')),
  data_url   text,
  updated_at timestamptz not null default now(),
  primary key (user_id, kind),
  -- The client caps a custom sound at 512KB; base64 inflates that by ~4/3.
  constraint user_assets_size check (data_url is null or length(data_url) <= 900000)
);

create trigger tasks_touch    before insert or update on public.tasks
  for each row execute function public.touch_updated_at();
create trigger projects_touch before insert or update on public.projects
  for each row execute function public.touch_updated_at();
create trigger settings_touch before insert or update on public.settings
  for each row execute function public.touch_updated_at();
create trigger assets_touch   before insert or update on public.user_assets
  for each row execute function public.touch_updated_at();

-- ── Row level security ──────────────────────────────────────────────────────
-- The anon key ships inside the JS bundle by design. RLS is the only thing
-- between one user's tasks and everyone else's.
--
-- `default auth.uid()` means the client never sends user_id, and `with check`
-- enforces it regardless. Update policies need BOTH `using` (which rows may be
-- targeted) and `with check` (what they may be set to) — omitting the latter
-- would let a client reassign its rows to another user.

alter table public.tasks       enable row level security;
alter table public.projects    enable row level security;
alter table public.sessions    enable row level security;
alter table public.point_ops   enable row level security;
alter table public.settings    enable row level security;
alter table public.user_assets enable row level security;

create policy tasks_select on public.tasks
  for select to authenticated using (auth.uid() = user_id);
create policy tasks_insert on public.tasks
  for insert to authenticated with check (auth.uid() = user_id);
create policy tasks_update on public.tasks
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy tasks_delete on public.tasks
  for delete to authenticated using (auth.uid() = user_id);

create policy projects_select on public.projects
  for select to authenticated using (auth.uid() = user_id);
create policy projects_insert on public.projects
  for insert to authenticated with check (auth.uid() = user_id);
create policy projects_update on public.projects
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy projects_delete on public.projects
  for delete to authenticated using (auth.uid() = user_id);

create policy settings_select on public.settings
  for select to authenticated using (auth.uid() = user_id);
create policy settings_insert on public.settings
  for insert to authenticated with check (auth.uid() = user_id);
create policy settings_update on public.settings
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy assets_select on public.user_assets
  for select to authenticated using (auth.uid() = user_id);
create policy assets_insert on public.user_assets
  for insert to authenticated with check (auth.uid() = user_id);
create policy assets_update on public.user_assets
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Immutable logs get select + insert only. The absence of update and delete
-- policies is the enforcement mechanism: those verbs are denied by default, so
-- focus history and the points ledger can be appended to but never rewritten,
-- even by a compromised client.
create policy sessions_select on public.sessions
  for select to authenticated using (auth.uid() = user_id);
create policy sessions_insert on public.sessions
  for insert to authenticated with check (auth.uid() = user_id);

create policy point_ops_select on public.point_ops
  for select to authenticated using (auth.uid() = user_id);
create policy point_ops_insert on public.point_ops
  for insert to authenticated with check (auth.uid() = user_id);

revoke all on public.tasks, public.projects, public.sessions,
              public.point_ops, public.settings, public.user_assets
  from anon;
